#Define version
version: "3.9"

#Define services
services:
  app:
    build: 
    # Build from Dockerfile in current directory
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "sudo python manage.py runserver 0.0.0.0:8000"

 